// This file is automatically generated. Do not edit it directly.
import { trackedFetch } from "@/lib/network";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// 30 days in seconds (for token expiry)
const THIRTY_DAYS_IN_SECONDS = 30 * 24 * 60 * 60; // 2,592,000 seconds

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      // Attempt to use longer session duration (server-side config takes precedence)
      detectSessionInUrl: true,
    },
    global: {
      fetch: trackedFetch,
    },
  },
);

// Extend session on app load to ensure 30-day validity
if (typeof window !== "undefined") {
  supabase.auth.getSession().then(async ({ data: { session } }) => {
    if (session) {
      // Attempt to refresh token to get fresh expiry
      await supabase.auth.refreshSession();
    }
  });
}
